#! /bin/bash

REGISTRY_URL=docker.youplus.cc
IMAGE_NAME=fake-api

function build {
    echo "Building docker image [$IMAGE_NAME]"
    docker build -t "$IMAGE_NAME" .
}

function usage {
    echo -e "Usage:"
    echo -e "\td.sh command <arguments>"
    echo -e ""
    echo -e "Commands:"
    echo -e "\tbuild            \t编译Docker镜像"
    echo -e "\trelease <VERSION>\t发布镜像到镜像服务器上"
}

function release {
    if [ $# -ne 2 ]; then
        usage
        exit
    fi
    echo "Releasing to $REGISTRY_URL, Version $2"
    DIST="$REGISTRY_URL/$IMAGE_NAME:$2"
    docker tag "$IMAGE_NAME" "$DIST"
    docker push "$DIST"
    echo $2 > VERSION
    git add VERSION
    git commit --amend --no-edit
}

case $1 in
    build)
        build
        ;;
    release)
        release $@
        ;;
    *)
        usage
        ;;
esac
